<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>lanelet2_rviz_display</name>
  <version>1.1.1</version>
  <description>RViz plugin to visualize Lanelet2 maps</description>

  <maintainer email="guido.linden@rwth-aachen.de">Guido Linden</maintainer>
  <author email="guido.linden@rwth-aachen.de">Guido Linden</author>

  <license>Apache-2.0</license>
  <license>BSD-3-Clause</license> <!-- lanelet2_map_helpers.hpp|cpp -->

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>lanelet2_core</depend>
  <depend>lanelet2_io</depend>
  <depend>lanelet2_map_interface</depend>
  <depend>lanelet2_projection</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rviz_common</depend>
  <depend>rviz_rendering</depend>
  <build_depend>qtbase5-dev</build_depend>
  <build_depend>rviz_ogre_vendor</build_depend>
  <exec_depend>libqt5-core</exec_depend>
  <exec_depend>libqt5-gui</exec_depend>
  <exec_depend>libqt5-opengl</exec_depend>
  <exec_depend>libqt5-widgets</exec_depend>
  <exec_depend>rviz_ogre_vendor</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_clang_format</test_depend>
  <test_depend>ament_cmake_clang_tidy</test_depend>
  <test_depend>ament_cmake_flake8</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
