include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  COMMAND: ros2 run lanelet2_map_server lanelet2_map_server
  PLATFORM: amd64
  ENABLE_INDUSTRIAL_CI: 'true'
  NOT_TEST_BUILD: 'true'
  ADDITIONAL_FILES_DIR: locations