<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lanelet2_utilities</name>
  <version>1.0.0</version>
  <description>The lanelet2_utilities package contains lanelet2 specific utility funtions</description>
  <maintainer email="guido.kueppers@ika.rwth-aachen.de">Guido Küppers</maintainer>
  <license>TODO: License declaration</license>

  <depend>lanelet2</depend>
  <depend>visualization_msgs</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
