/**/*:
  ros__parameters:
    left_bound_line_width: 0.1
    left_bound_color_hex: "#0000FF"
    left_bound_line_opacity: 0.5

    right_bound_line_width: 0.1
    right_bound_color_hex: "#FF0000"
    right_bound_line_opacity: 0.5

    centerline_line_width: 0.08
    centerline_color_hex: "#008000"
    centerline_opacity: 0.4

    reference_line_width: 0.2
    reference_line_color_hex: "#FFFF00"
    reference_line_opacity: 0.5

    # Mesh resources can be loaded via https, (ros-)package and file, but package and file links only work in the Desktop application.
    # See: https://docs.foxglove.dev/docs/visualization/panels/3d
    # Also: https://foxglove.dev/blog/how-to-visualize-ros-mesh-markers
    traffic_light_mesh_resource: "https://raw.githubusercontent.com/sdamaschke/ika_meshes/main/meshes/tricolor_tl/tricolor_traffic_light.glb"
    traffic_light_scale: 1.0
    traffic_light_z_offset: 1.3
    traffic_light_opacity: 1.0
