services:

  lanelet2-map-server:
    image: ghcr.io/openads-project/lanelet2_map_server:v1.2.2
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command: |
      ros2 launch lanelet2_map_server lanelet2_map_server_launch.py
        namespace:=/localization

  rviz:
    image: ghcr.io/openads-project/monitoring:v1.0.0
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      DISPLAY: ${DISPLAY}
    command: rviz2 -d /config.rviz
    volumes:
      - ./rviz/config.rviz:/config.rviz
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
