services:

  lanelet2-map-server:
    # TODO: github image
    image: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/localization/lanelet2_map_server:latest_open-source_ci-amd64 # v1.1.1
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    command: |
      ros2 launch lanelet2_map_server lanelet2_map_server_launch.py
        namespace:=/localization
    volumes:
      - ./lanelet2_map_server/params.yml:/docker-ros/ws/install/lanelet2_map_server/share/lanelet2_map_server/config/params.yml
      - ./lanelet2_map_server/maps:/data/maps

  rviz:
    image: ghcr.io/openads-project/lanelet2_route_planning:demo-monitoring
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      DISPLAY: ${DISPLAY}
    command: rviz2 -d /config.rviz
    volumes:
      - ./rviz/config.rviz:/config.rviz
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
